# Generated by Django 5.0.1 on 2024-01-06 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(help_text='Supplier of Order', on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier'),
        ),
    ]
